//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public Comanda()
        {
            this.LineaComandas = new HashSet<LineaComanda>();
        }
    
        public int ComandaId { get; set; }
        public int NumeroServicio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Dispositivo { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaTurno { get; set; }
        public int EmpresaId { get; set; }
    
        public virtual Turno Turno { get; set; }
        public virtual ICollection<LineaComanda> LineaComandas { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
