//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Administradors = new HashSet<Administrador>();
            this.Categorias = new HashSet<Categoria>();
            this.Comandas = new HashSet<Comanda>();
            this.Promocions = new HashSet<Promocion>();
            this.RegistroEliminacions = new HashSet<RegistroEliminacion>();
            this.Socios = new HashSet<Socio>();
            this.Turnoes = new HashSet<Turno>();
            this.Usuarios = new HashSet<Usuario>();
            this.Productoes = new HashSet<Producto>();
            this.LineaComandas = new HashSet<LineaComanda>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Rut { get; set; }
        public string RazonSocial { get; set; }
    
        public virtual ICollection<Administrador> Administradors { get; set; }
        public virtual ICollection<Categoria> Categorias { get; set; }
        public virtual ICollection<Comanda> Comandas { get; set; }
        public virtual ICollection<Promocion> Promocions { get; set; }
        public virtual ICollection<RegistroEliminacion> RegistroEliminacions { get; set; }
        public virtual ICollection<Socio> Socios { get; set; }
        public virtual ICollection<Turno> Turnoes { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<Producto> Productoes { get; set; }
        public virtual ICollection<LineaComanda> LineaComandas { get; set; }
    }
}
