//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.LineaComandas = new HashSet<LineaComanda>();
            this.Promocions = new HashSet<Promocion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public int CategoriaId { get; set; }
        public int EmpresaId { get; set; }
        public System.DateTime FechaSincro { get; set; }
        public bool Activo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<LineaComanda> LineaComandas { get; set; }
        public virtual ICollection<Promocion> Promocions { get; set; }
    }
}
