//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public double PorcentajeDesc { get; set; }
        public decimal ImporteDesc { get; set; }
        public int EmpresaId { get; set; }
        public System.DateTime FechaSincro { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
