//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnight
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartnightEntities : DbContext
    {
        public SmartnightEntities()
            : base("name=SmartnightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administradors { get; set; }
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Comanda> Comandas { get; set; }
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<LineaComanda> LineaComandas { get; set; }
        public DbSet<Producto> Productoes { get; set; }
        public DbSet<Promocion> Promocions { get; set; }
        public DbSet<RegistroEliminacion> RegistroEliminacions { get; set; }
        public DbSet<Socio> Socios { get; set; }
        public DbSet<Turno> Turnoes { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
