//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Turnoes = new HashSet<Turno>();
        }
    
        public int Id { get; set; }
        public string Pin { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int EmpresaId { get; set; }
        public System.DateTime FechaSincro { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Turno> Turnoes { get; set; }
    }
}
